version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=ticketsdb_2
      - POSTGRES_USER=jcjimenez
      - POSTGRES_PASSWORD=G17Sh3yEOFhW5hne
    ports:
      - "5432:5432"
    volumes:
      - ./v2_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U jcjimenez -d ticketsdb
      interval: 5s
      timeout: 5s
      retries: 5
  bff-scan-tickets_2:
    container_name: bff-scan-tickets_2
    image: bff-scan-tickets:2.0.0
    restart: unless-stopped
    ports:
      - 8082:8082
    depends_on:
      postgres_2:
        condition: service_healthy
    command: sh -c "/wait"
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=jcjimenez
      - TYPEORM_PASSWORD=G17Sh3yEOFhW5hne
      - TYPEORM_DATABASE=ticketsdb_2
      - TYPEORM_PORT=5433
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=src/**/*entity.ts
      - TYPEORM_MIGRATIONS=src/database/migrations/*.ts
      - TYPEORM_MIGRATIONS_DIR=src/database/migrations
      - TYPEORM_MIGRATIONS_TABLE_NAME=migrations
      - APP_PORT=8082
      - JWT_SECRET=5c4nt1ck3ts
      - EMAIL_SENDER_USER=enterprisetheboys@gmail.com
      - EMAIL_SENDER_PASSWORD=ashley.13
      - JWT_EXPIRES_IN=20m
  fe-scan-tickets_2:
    container_name: fe-scan-tickets_2
    image: fe-scan-tickets:2.0.0
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - "bff-scan-tickets_2"
