version: "3.3"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ticketsdb
      - POSTGRES_USER=jcjimenez
      - POSTGRES_PASSWORD=G17Sh3yEOFhW5hne
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgres/data
    healthcheck:
      test: pg_isready -U jcjimenez -d ticketsdb
      interval: 5s
      timeout: 5s
      retries: 5
  bff-scan-tickets:
    container_name: bff-scan-tickets
    build: ../bff-scan-tickets
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "/wait"
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=jcjimenez
      - TYPEORM_PASSWORD=G17Sh3yEOFhW5hne
      - TYPEORM_DATABASE=ticketsdb
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=src/**/*entity.ts
      - TYPEORM_MIGRATIONS=src/database/migrations/*.ts
      - TYPEORM_MIGRATIONS_DIR=src/database/migrations
      - TYPEORM_MIGRATIONS_TABLE_NAME=migrations
      - APP_PORT=8081
      - JWT_SECRET=5c4nt1ck3ts
      - EMAIL_SENDER_USER=enterprisetheboys@gmail.com
      - EMAIL_SENDER_PASSWORD=ashley.13
      - JWT_EXPIRES_IN=10m
  fe-scan-tickets:
    container_name: fe-scan-tickets
    build: ../fe-scan-tickets
    restart: unless-stopped
    ports:
      - 443:443
    depends_on:
      - "bff-scan-tickets"

